import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      ".next/**",
      // Static export output: generated, minified, and a copy of public/.
      "out/**",
      "node_modules/**",
      ".emulator-data/**",
      // Generated by Next.js on every build; its triple-slash references are
      // not ours to fix.
      "next-env.d.ts",
      // Service worker: runs in a worker scope, not a browser/Node one.
      "public/sw.js",
    ],
  },
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];

export default eslintConfig;
